### ISSUE TITLE
Are the polarities of the resets correct in the cover() statements ?

### ISSUE THREAD

**Issue by fredrequin** [ZipCPU/website#4]
Hello,
I am wondering if these two cover() statements are correct 

https://github.com/ZipCPU/website/blob/fc453a09d181f5bffe91fcd87f214950caa756d2/examples/afifo.v#L666
https://github.com/ZipCPU/website/blob/fc453a09d181f5bffe91fcd87f214950caa756d2/examples/afifo.v#L669

Best regards,
Frédéric Requin

**Comment by ZipCPU** [comment]
Looking over those resets now, I'm wondering the same thing.  ;)

Let's see ... what would we want to be able to cover?

1. An initial reset
2. Leaving that initial reset
3. A design entering a reset after running for some time

Perhaps I should adjust this cover statement to check all three conditions?

Dan

**Comment by ZipCPU** [comment]
Upon further review, the cover statements are correct as written.  They are not covering whether or not the design can enter into a reset, but rather that the design can properly leave the reset condition.  This is a check against the assumptions of the design, placed in there because my assumptions initially overconstrained the design keeping it from ever leaving reset in the first place.
